baseURL: "https://yan-zhou-website.netlify.app"
languageCode: en-us
title: "Yan Zhou"
theme: archie
copyright: © Athul
pygmentsstyle: monokai
pygmentscodefences: yes
pygmentscodefencesguesssyntax: yes
enableEmoji: true
params:
  mode: toggle
  social:
    - icon: github
      name: GitHub
      url: https://github.com/ryanzhou0915
    #- icon: twitter
     # name: Twitter
      #url: https://twitter.com/athulcajay/
   # - icon: gitlab
    #  name: GitLab
     # url: https://gitlab.com/athul/
  subtitle: Welcome to my website! Please view my ongoing research projects below!
  useCDN: no
  customCSS:
    - css/customize.css
menu:
  main:
    - name: Home
      url: "/"
      weight: 1
    - name: Projects
      url: "/projects"
      weight: 2
    - name: Courses
      url: "/courses"
      weight: 3
    - name: Tags
      url: "/tags"
      weight: 4
